language: python
before_install:
   - sudo apt install -yq libvirt-bin virtinst libvirt0 libvirt-dev
   - cat requirements.system | sudo xargs apt -yq install
install:
   - pip install tox-travis
script:
   - cd testpool/db; python ./manager.py syncdb --noinput
   - tox
