language: python
install:
   - sudo apt install -yq libvirt-bin virtinst libvirt0 libvirt-dev enchant
   - cat requirements.system | sudo xargs apt -yq install
   - pip install tox-travis
   - pip install -r requirements.txt
   - pip install -r requirements.dev
script:
   - cd testpool/db ; ./manage.py syncdb --noinput
   - make check
   - make deb.build
   - make rpm.build
