language: python
install:
   - sudo apt install -yq libvirt-bin virtinst libvirt0 libvirt-dev
   - cat requirements.system | sudo xargs apt -yq install
   - pip install tox-travis
script:
   - cd testpool/db; python ./manage.py test 
   - cd testpool/db; python ./manage.py syncdb --noinput
   - make pylint pep8
   - tox
