language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip install -qr requirements.txt
  - pip install -qr requirements.dev
script:
  - make pylint pycodestyle
  - make deb.build
