language: python
python:
  - "2.7"
before_install:
  - sudo -H apt-get update -qq
  - sudo -H cat requirements.system | sudo xargs apt-get -y install
install:
  - pip install -qr requirements.txt
  - pip install -qr requirements.dev
script:
  - make pylint pycodestyle
  - make deb.build
