language: python
before_install:
   - sudo apt-get install libvirt-bin virtinst libvirt0 libvirt-dev
   - cat requirements.system | sudo xargs apt-get -y install
install:
   - pip install tox-travis
script:
   - tox
