language: python
python:
  - "2.7"
install:
  - sudo -H pip install --upgrade pip
  - sudo -H pip install -qr requirements.txt -qr requirements.dev
script:
  - make pylint pycodestyle
  - make deb.build
